# config/database.yml

default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

production:
  primary: &primary
    <<: *default
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *primary

  cache:
    <<: *primary