Club.create!(name: "Oxford", supplies_towels: false, notes: "No complaining about the tambour")
Club.create!(name: "Queens Club", supplies_towels: true, notes: "Big and fluffy, in two sizes")
Club.create!(name: "Jesmond Dene", supplies_towels: true, notes:"Don't mix up court towels with normal towels")
Club.create!(name: "Leamington", supplies_towels: true, notes: "A tasteful blue")
Club.create!(name: "Moreton Morrell", supplies_towels: false, notes:"Not even for the world championship")
Club.create!(name: "Hardwick", supplies_towels: true, notes: "Surprising")
Club.create!(name: "Lords", supplies_towels: true, notes: "Nice baths, too")
Club.create!(name: "Radley", supplies_towels: false, notes: "CJR doesn't approve")
Club.create!(name: "RTC", supplies_towels: false, notes: "I guess Prince Albert brought his own")
Club.create!(name: "Prested Hall", supplies_towels: false, notes: "Not even stripy ones")
Club.create!(name: "Holyport", supplies_towels: true, notes: "For Apres Ski")
Club.create!(name: "Paris", supplies_towels: true, notes: "Beaucoup")
Club.create!(name: "Cambridge", supplies_towels: false, notes: "Neither green nor blue")
Club.create!(name: "Bristol", supplies_towels: false, notes: "They do have an in-house physio though")
Club.create!(name: "Manchester", supplies_towels: true, notes: "Don't use white towels to mop up spilled claret, please")    